//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nol_Adin_Sabirov.Misc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ychetnaya
    {
        public int IdZapis { get; set; }
        public int IdReysa { get; set; }
        public Nullable<System.DateTime> DateVilet { get; set; }
        public Nullable<int> PriceTicket { get; set; }
        public Nullable<int> KolVoSells { get; set; }
    
        public virtual Spravochnaya Spravochnaya { get; set; }
    }
}
